site_name: Linux
site_url: https://linux.rafaeldutra.me
theme:
  language: pt-BR
  name: material
  logo: assets/tux-icon.png
  favicon: assets/tux-icon.png
  features:
    - navigation.sections
    - navigation.expand
    - navigation.footer
