site_name: Linux
site_url: https://linux.rafaeldutra.me
theme:
  name: material
  logo: assets/tux-icon.png
  favicon: assets/tux-icon.png
  features:
    - navigation.sections
    - navigation.expand
    - navigation.footer
    - content.code.annotate
    - content.code.copy
    - content.code.select
